# Generated by Django 6.0.1 on 2026-01-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_price_competitor_brand_price_competitor_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'cities',
            },
        ),
        migrations.AlterModelOptions(
            name='aggregator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='importjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productlink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unitconversion',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='price',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'aggregator', 'city')},
        ),
    ]
