import { createContext, useContext, useState, useEffect } from "react";

// Translation strings for 3 languages
const translations = {
  ru: {
    // Sidebar
    dashboard: "Дашборд",
    comparison: "Сравнение цен",
    recommendations: "Рекомендации",
    analytics: "Аналитика",
    database: "База данных",
    mappingReview: "Проверка маппинга",
    priceAnalyst: "Ценовой аналитик",
    glovoPartner: "Партнёр Ryadom",
    optimizeForTop1: "Оптимизация для позиции №1",

    // Dashboard
    dashboardTitle: "Дашборд",
    dashboardSubtitle: "Следите за своей позицией на рынке в реальном времени",
    refresh: "Обновить",
    totalProducts: "Всего товаров",
    inAssortment: "В ассортименте",
    top1Position: "Позиция ТОП 1",
    ofCatalog: "нашего каталога",
    needAction: "Требуют действий",
    priceAdjustment: "Нужна корректировка цены",
    missing: "Отсутствуют",
    competitorsOnly: "Только у конкурентов",
    awaitingDecision: "Ожидают решения",
    awaitingActions: "Ожидают действий",
    potentialSavings: "Потенциальная экономия",
    ifApplyAll: "Если применить все",
    marketCoverage: "Покрытие рынка",
    inStock: "Товаров в наличии",
    priceCompetitiveness: "Ценовая конкурентность",
    inTop1: "В позиции ТОП 1",
    statusDistribution: "Распределение статусов товаров",
    marketCoverageComparison: "Сравнение покрытия рынка",
    priceComparison: "Сравнение цен",
    viewAll: "Смотреть все",
    minPrice: "Минимальная цена",
    productsCount: "товаров",
    leader: "Лидер",
    higherThanLeader: "Дороже лидера",
    moreExpensiveThan: "Дороже чем",
    totalAssortment: "Общий ассортимент",
    inShopSample: "В выборке магазина",
    marketPositioning: "Позиционирование на рынке",
    top1Leader: "ТОП-1 (Лидер)",
    aboveMarket: "Выше рынка",
    missed: "Упущено",
    activeSources: "Активные источники",
    ryadom: "Рядом",

    // Comparison
    comparisonTitle: "Мониторинг цен",
    comparisonSubtitle: "Сравните цены на всех агрегаторах",
    export: "Экспорт",
    searchProducts: "Поиск товаров...",
    allCategories: "Все категории",
    all: "Все",
    top1: "ТОП 1",
    needActionFilter: "Требуют действий",
    missingFilter: "Отсутствуют",
    showPerUnit: "Показать за кг/л",
    product: "Товар",
    ourPosition: "Наша позиция",
    noProductsFound: "Товары не найдены",
    min: "МИН",
    link: "Ссылка",
    page: "Стр.",
    of: "из",
    back: "Назад",
    next: "Вперед",
    resetFilters: "Сбросить фильтры",
    noProductsMatch: "Нет товаров, соответствующих вашим фильтрам",

    // ComparisonTable
    noPrice: "Нет цены",
    exclusive: "Эксклюзив",
    bestPrice: "Лучшая цена",
    moreExpensiveBy: "Дороже на",
    ok: "Ок",
    pricePerUnit: "Цена за ед.",
    pricePerItem: "Цена за шт",
    noDataToDisplay: "Нет данных для отображения",

    // Recommendations
    recommendationsTitle: "Рекомендации",
    recommendationsSubtitle:
      "AI-рекомендации по ценообразованию для достижения ТОП-1",
    showVisualization: "Показать визуализацию",
    hideVisualization: "Скрыть визуализацию",
    runAlgorithm: "Запустить алгоритм",
    running: "Выполняется...",
    total: "Всего",
    pending: "В ожидании",
    applied: "Применено",
    rejected: "Отклонено",
    lowerPrice: "Сниженная цена",
    addProduct: "Добавить продукт",
    current: "Текущая",
    recommended: "Рекомендуемая",
    notInStock: "Нет в наличии",
    savings: "Экономия",
    minCompetitor: "Мин. у конкурентов",
    lowerBy: "ниже",
    apply: "Применить",
    applying: "Применение...",
    reject: "Отклонить",
    successApplied: "Успешно применено",
    noRecommendations: "Вы лидируете! 🎉",
    noRecommendationsDesc:
      "Нет рекомендаций — все ваши цены уже конкурентоспособны",

    // Priority
    high: "Высокий",
    medium: "Средний",
    low: "Низкий",

    // Analytics
    analyticsTitle: "Аналитика рынка",
    analyticsSubtitle: "Детальный разбор ценовых позиций",
    recommendationsTitle: "Рекомендации",
    pricingRecommendations: "AI-рекомендации по ценообразованию",
    hideVisualization: "Скрыть визуализацию",
    showVisualization: "Показать визуализацию",
    runAlgorithm: "Запустить алгоритм",
    running: "Выполняется...",
    total: "Всего",
    all: "Все",
    waiting: "В ожидании",
    applied: "Применено",
    rejected: "Отклонено",
    lowerPrice: "Сниженная цена",
    addProduct: "Добавить продукт",
    top1coverage: "Охват ТОП-1",
    importFromApi: "Импорт из API",
    confirmRunMatching: "Запустить процесс AI матчинга товаров? Это может занять время.",
    matchingStarted: "Процесс матчинга запущен в фоновом режиме! Вы можете следить за прогрессом на странице Сравнения цен или Аналитики.",
    errorMatching: "Ошибка при запуске матчинга: ",
    confirmRunImport: "Запустить импорт данных из API?",
    importStarted: "Импорт запущен в фоновом режиме. Прогресс можно смотреть на странице Аналитики или Сравнения цен.",
    errorImport: "Ошибка при запуске импорта: ",
    productCount: "Количество товаров",
    importDataTitle: "Импорт данных",
    importJsonDesc: "Импорт товаров из JSON файлов",
    dragDropFile: "Перетащите файл сюда или нажмите для выбора",
    jsonFileLabel: "JSON файл",
    testRun: "Тестовый запуск (без сохранения)",
    analyzing: "Анализ...",
    importing: "Импорт...",
    verify: "Проверить",
    importAction: "Импортировать",
    analysisCompleted: "Анализ завершен",
    importCompleted: "Импорт завершен",
    totalFound: "Всего найдено",
    willBeImported: "Будет импортировано",
    successfully: "Успешно",
    errorsCount: "Ошибок",
    more: "еще",
    byAggregators: "По агрегаторам:",
    byCategories: "По категориям:",
    errorsLabel: "Ошибки:",
    uploadAnotherFile: "Загрузить другой файл",
    schema: "Схема",
    records: "записей",
    name: "Название",
    color: "Цвет",
    ourCompany: "Наша компания",
    yes: "Да",
    no: "Нет",
    icon: "Иконка",
    category: "Категория",
    position: "Позиция",
    databaseTitle: "Управление базой данных",
    databaseSubtitle: "Просмотр и импорт данных",
    loading: "Загрузка",
    loadingDesc: "Загрузка товаров и цен со всех агрегаторов",
    analysis: "Анализ",
    analysisDesc: "Сравнение цен конкурентов",
    scarcitySearch: "Поиск дефицита",
    scarcitySearchDesc: "Поиск отсутствующих товаров в нашем каталоге",
    calculation: "Расчёт",
    calculationDesc: "Вычисление оптимальных цен для ТОП-1",
    generation: "Генерация",
    generationDesc: "Создание рекомендаций к действию",
    visualizationTitle: "Визуализация алгоритма",
    visualizationDesc: "Посмотрите, как Pricent анализирует цены в реальном времени",
    pause: "Пауза",
    reset: "Сбросить",
    analysisResults: "Результаты анализа:",
    analysisCompletedLong: "Анализ завершён!",
    recommendationsFound: "Найдено {count} рекомендаций для достижения ТОП-1",
    searchCategories: "Поиск категорий...",
    selectAll: "Выбрать все",
    deselectAll: "Снять выделение",
    nothingFound: "Ничего не найдено",
    openOn: "Открыть на",
    noData: "Нет данных",
    noDataDesc: "Данные пока отсутствуют",
    productsNotFound: "Товары не найдены",
    tryChangeFilters: "Попробуйте изменить параметры поиска или сбросить фильтры",
    verified: "Проверено",
    totalCorrections: "Всего исправлений",
    resetFilters: "Сбросить фильтры",
    dataUnavailable: "Данные недоступны",
    uploadDataDesc: "Загрузите данные через раздел 'База данных' для начала работы",
    emptyCategoryTitle: "Категория пуста",
    emptyCategoryDesc: "В этой категории пока нет товаров",
    whatChartMeans: "Что означает график",
    chartExplanation: "показывает количество товаров у каждого конкурента. Чем больше ассортимент — тем сильнее конкурент на рынке.",
    errorDuringVerification: "Ошибка при проверке: ",
    errorSaving: "Ошибка сохранения: ",
    errorDeleting: "Ошибка удаления: ",
    editMatch: "Изменить матч",
    alreadyInDatabase: "уже в базе",
    priceDynamics: "Динамика цен",
    marketShare: "Доля рынка",
    marketGaps: "Пробелы на рынке",
    top5Gaps: "Топ 5 упущенных возможностей",
    missedOpportunities: "Упущенные возможности",
    competitorsProducts: "Товары, которые есть у конкурентов",
    collapse: "Свернуть",
    gapAnalysis: "Анализ пробелов",
    gapAnalysisDesc: "Здесь собраны товары, которые представлены у большинства ваших конкурентов. Добавление этих позиций поможет увеличить ваш охват и привлечь новых покупателей.",
    popularity: "Популярность",
    minPriceShort: "Мин. цена",
    aggregatorsCount: "агрегаторов",
    noGapsToDisplay: "Нет пропущенных товаров для отображения",
    matchingInProgress: "AI подбор товаров в процессе...",
    matchingCompleted: "Подбор завершён",
    initializing: "Инициализация...",
    matched: "совпадений",
    processed: "обработано",
    errors: "Ошибки",
    importInProgress: "Импорт данных из API...",
    importCompleted: "Импорт завершён",
    preparing: "Подготовка...",
    files: "Файлы",
    items: "товаров",
    productsLower: "товаров",
    competitorsAssortment: "Ассортимент конкурентов",
    productsPerAggregator: "Количество товаров у каждого агрегатора",
    whatChartMeans: "Что означает график",
    chartExplanation: "показывает количество товаров у каждого конкурента. Чем больше ассортимент — тем сильнее конкурент на рынке.",
    productsUpper: "ТОВАРОВ",
    noOverlapData: "Нет данных о пересечении ассортимента",
    loadingAnalytics: "Загрузка аналитики...",

    // Mapping Review
    mappingReviewTitle: "Проверка маппинга",
    mappingReviewSubtitle: "Перепроверка замапленных товаров. Источник: bq-results (уже в базе).",
    correctVerdict: "Корректно",
    needsReviewVerdict: "Проверить",
    errorVerdict: "Ошибка",
    unmappedVerdict: "Не замаплено",
    notFoundVerdict: "Не найдено",
    correctedVerdict: "Исправлено",
    deletedVerdict: "Удалено",
    refreshList: "Обновить список",
    mappedFilesFromApi: "Mapped-файлы из API",
    selectMappedFile: "Выбери mapped-файл",
    selectMappedFileAlert: "Выбери mapped-файл из списка",
    selectFilePlaceholder: "-- Выбери файл --",
    limitRecords: "Лимит записей",
    verifyFromApi: "Проверить из API",
    sourceLabel: "Источник",
    verifiedSummary: "Проверено",
    totalCorrections: "Всего исправлений",
    searchPlaceholderMapping: "Поиск по названию или причине...",
    allStatuses: "Все статусы",
    editMatch: "Изменить матч",
    deleteMatch: "Удалить матч",
    correctedManually: "Исправлено вручную",
    matchDeleted: "Матч удалён (нет соответствия)",
    minSearchChars: "Введите минимум 2 символа для поиска",
    verdict: "Вердикт",
    sourceRyadom: "Источник (Рядом)",
    match: "Матч",
    reason: "Причина",
    actions: "Действия",
    searchRyadomProducts: "Поиск товара из Рядом...",

    // Database
    databaseTitle: "База данных",
    databaseSubtitle: "Управление данными о товарах, ценах и агрегаторах",
    import: "Импорт",
    downloadTemplate: "Скачать шаблон",
    products: "Товары",
    prices: "Цены",
    links: "Ссылки",
    categories: "Категории",
    aggregators: "Агрегаторы",
    name: "Название",
    color: "Цвет",
    ourCompany: "Наша компания",
    yes: "Да",
    no: "Нет",
    icon: "Иконка",
    category: "Категория",
    position: "Позиция",
    action: "Действие",
    status: "Статус",
    priority: "Приоритет",
    schema: "Схема",
    tables: "Таблиц",
    totalRecords: "Всего записей",
    records: "записей",

    // Common
    selectAll: "Выбрать все",
    clearSelection: "Снять выделение",
    noData: "Нет данных",
    loading: "Загрузка...",
    error: "Ошибка",
    success: "Успешно",
    cancel: "Отмена",
    save: "Сохранить",
    delete: "Удалить",
    edit: "Редактировать",
    close: "Закрыть",
    light: "Светлая",
    dark: "Темная",
  },

  en: {
    // Sidebar
    dashboard: "Dashboard",
    comparison: "Price Comparison",
    recommendations: "Recommendations",
    analytics: "Analytics",
    database: "Database",
    mappingReview: "Mapping Review",
    priceAnalyst: "Price Analyst",
    glovoPartner: "Ryadom Partner",
    optimizeForTop1: "Optimize for #1 position",

    // Dashboard
    dashboardTitle: "Dashboard",
    dashboardSubtitle: "Monitor your market position in real-time",
    refresh: "Refresh",
    totalProducts: "Total Products",
    inAssortment: "In assortment",
    top1Position: "TOP 1 Position",
    ofCatalog: "of our catalog",
    needAction: "Need Action",
    priceAdjustment: "Price adjustment needed",
    missing: "Missing",
    competitorsOnly: "Competitors only",
    awaitingDecision: "Awaiting Decision",
    awaitingActions: "Awaiting actions",
    potentialSavings: "Potential Savings",
    ifApplyAll: "If apply all",
    marketCoverage: "Market Coverage",
    inStock: "Products in stock",
    priceCompetitiveness: "Price Competitiveness",
    inTop1: "In TOP 1 position",
    statusDistribution: "Product Status Distribution",
    marketCoverageComparison: "Market Coverage Comparison",
    priceComparison: "Price Comparison",
    viewAll: "View all",
    minPrice: "Minimum price",
    productsCount: "products",
    leader: "Leader",
    higherThanLeader: "Higher than leader",
    moreExpensiveThan: "More expensive than",
    totalAssortment: "Total assortment",
    inShopSample: "In store sample",
    marketPositioning: "Market Positioning",
    top1Leader: "TOP-1 (Leader)",
    aboveMarket: "Above market",
    missed: "Missed",
    activeSources: "Active sources",
    ryadom: "Ryadom",

    // Comparison
    comparisonTitle: "Price Monitoring",
    comparisonSubtitle: "Compare prices across all aggregators",
    export: "Export",
    searchProducts: "Search products...",
    allCategories: "All categories",
    all: "All",
    top1: "TOP 1",
    needActionFilter: "Need action",
    missingFilter: "Missing",
    showPerUnit: "Show per kg/l",
    product: "Product",
    ourPosition: "Our Position",
    noProductsFound: "No products found",
    min: "MIN",
    link: "Link",
    page: "Page",
    of: "of",
    back: "Back",
    next: "Next",
    resetFilters: "Reset filters",
    noProductsMatch: "No products match your filters",

    // ComparisonTable
    noPrice: "No price",
    exclusive: "Exclusive",
    bestPrice: "Best price",
    moreExpensiveBy: "More expensive by",
    ok: "Ok",
    pricePerUnit: "Price per unit",
    pricePerItem: "Price per item",
    noDataToDisplay: "No data to display",

    // Recommendations
    recommendationsTitle: "Recommendations",
    recommendationsSubtitle: "AI-powered pricing recommendations for TOP 1",
    showVisualization: "Show visualization",
    hideVisualization: "Hide visualization",
    runAlgorithm: "Run Algorithm",
    running: "Running...",
    total: "Total",
    pending: "Pending",
    applied: "Applied",
    rejected: "Rejected",
    lowerPrice: "Lower price",
    addProduct: "Add product",
    current: "Current",
    recommended: "Recommended",
    notInStock: "Not in stock",
    savings: "Savings",
    minCompetitor: "Min. competitor",
    lowerBy: "lower",
    apply: "Apply",
    applying: "Applying...",
    reject: "Reject",
    successApplied: "Successfully applied",
    noRecommendations: "You're leading! 🎉",
    noRecommendationsDesc:
      "No recommendations — all your prices are already competitive",

    // Priority
    high: "High",
    medium: "Medium",
    low: "Low",

    // Analytics
    analyticsTitle: "Market Analytics",
    analyticsSubtitle: "Detailed breakdown of price positions",
    recommendationsTitle: "Recommendations",
    pricingRecommendations: "AI-pricing recommendations",
    hideVisualization: "Hide visualization",
    showVisualization: "Show visualization",
    runAlgorithm: "Run algorithm",
    running: "Running...",
    total: "Total",
    all: "All",
    waiting: "Pending",
    applied: "Applied",
    rejected: "Rejected",
    lowerPrice: "Lower price",
    addProduct: "Add product",
    top1coverage: "TOP-1 coverage",
    importFromApi: "Import from API",
    confirmRunMatching: "Start AI product matching process? This may take some time.",
    matchingStarted: "Matching process started in background! You can follow the progress on the Price Comparison or Analytics page.",
    errorMatching: "Error starting matching: ",
    confirmRunImport: "Start data import from API?",
    importStarted: "Import started in background. Progress can be viewed on the Analytics or Price Comparison page.",
    errorImport: "Error starting import: ",
    productCount: "Product count",
    importDataTitle: "Data Import",
    importJsonDesc: "Import products from JSON files",
    dragDropFile: "Drag and drop file here or click to select",
    jsonFileLabel: "JSON file",
    testRun: "Test run (no saving)",
    analyzing: "Analyzing...",
    importing: "Importing...",
    verify: "Verify",
    importAction: "Import",
    analysisCompleted: "Analysis completed",
    importCompleted: "Import completed",
    totalFound: "Total found",
    willBeImported: "Will be imported",
    successfully: "Successfully",
    errorsCount: "Errors",
    more: "more",
    byAggregators: "By aggregators:",
    byCategories: "By categories:",
    errorsLabel: "Errors:",
    uploadAnotherFile: "Upload another file",
    schema: "Schema",
    records: "records",
    name: "Name",
    color: "Color",
    ourCompany: "Our company",
    yes: "Yes",
    no: "No",
    icon: "Icon",
    category: "Category",
    position: "Position",
    databaseTitle: "Database Management",
    databaseSubtitle: "View and import data",
    loading: "Loading",
    loadingDesc: "Loading products and prices from all aggregators",
    analysis: "Analysis",
    analysisDesc: "Comparing competitor prices",
    scarcitySearch: "Scarcity search",
    scarcitySearchDesc: "Finding missing products in our catalog",
    calculation: "Calculation",
    calculationDesc: "Calculating optimal prices for TOP-1",
    generation: "Generation",
    generationDesc: "Creating actionable recommendations",
    visualizationTitle: "Algorithm Visualization",
    visualizationDesc: "See how Pricent analyzes prices in real-time",
    pause: "Pause",
    reset: "Reset",
    analysisResults: "Analysis results:",
    analysisCompletedLong: "Analysis completed!",
    recommendationsFound: "Found {count} recommendations for TOP-1",
    searchCategories: "Search categories...",
    selectAll: "Select all",
    deselectAll: "Deselect all",
    nothingFound: "Nothing found",
    openOn: "Open on",
    noData: "No data",
    noDataDesc: "Data is currently missing",
    productsNotFound: "Products not found",
    tryChangeFilters: "Try changing search parameters or resetting filters",
    verified: "Verified",
    totalCorrections: "Total corrections",
    resetFilters: "Reset filters",
    dataUnavailable: "Data unavailable",
    uploadDataDesc: "Upload data through the 'Database' section to get started",
    emptyCategoryTitle: "Category is empty",
    emptyCategoryDesc: "There are no products in this category yet",
    whatChartMeans: "What the chart means",
    chartExplanation: "shows the number of products for each competitor. The larger the range, the stronger the competitor in the market.",
    errorDuringVerification: "Error during verification: ",
    errorSaving: "Error saving: ",
    errorDeleting: "Error deleting: ",
    editMatch: "Edit match",
    alreadyInDatabase: "already in database",
    priceDynamics: "Price Dynamics",
    marketShare: "Market Share",
    marketGaps: "Market Gaps",
    top5Gaps: "Top 5 missed opportunities",
    missedOpportunities: "Missed opportunities",
    competitorsProducts: "Products available from competitors",
    collapse: "Collapse",
    gapAnalysis: "Gap Analysis",
    gapAnalysisDesc: "These are products represented by most of your competitors. Adding these items will help increase your coverage and attract new customers.",
    popularity: "Popularness",
    minPriceShort: "Min. price",
    aggregatorsCount: "aggregators",
    noGapsToDisplay: "No missing products to display",
    matchingInProgress: "AI Product Matching in Progress...",
    matchingCompleted: "Matching Completed",
    initializing: "Initializing...",
    matched: "matched",
    processed: "processed",
    errors: "Errors",
    importInProgress: "Importing data from API...",
    importCompleted: "Import Completed",
    preparing: "Preparing...",
    files: "Files",
    items: "items",
    productsLower: "products",
    competitorsAssortment: "Competitors Assortment",
    productsPerAggregator: "Number of products for each aggregator",
    whatChartMeans: "What the chart means",
    chartExplanation: "shows the number of products for each competitor. The larger the assortment, the stronger the competitor in the market.",
    productsUpper: "PRODUCTS",
    noOverlapData: "No assortment overlap data",
    loadingAnalytics: "Loading analytics...",

    // Mapping Review
    mappingReviewTitle: "Mapping Review",
    mappingReviewSubtitle: "Re-checking mapped products. Source: bq-results (already in database).",
    correctVerdict: "Correct",
    needsReviewVerdict: "Check",
    errorVerdict: "Error",
    unmappedVerdict: "Unmapped",
    notFoundVerdict: "Not found",
    correctedVerdict: "Corrected",
    deletedVerdict: "Deleted",
    refreshList: "Refresh list",
    mappedFilesFromApi: "Mapped files from API",
    selectMappedFile: "Select mapped file",
    selectMappedFileAlert: "Select mapped file from the list",
    selectFilePlaceholder: "-- Select file --",
    limitRecords: "Records limit",
    verifyFromApi: "Verify from API",
    sourceLabel: "Source",
    verifiedSummary: "Verified",
    totalCorrections: "Total corrections",
    searchPlaceholderMapping: "Search by name or reason...",
    allStatuses: "All statuses",
    editMatch: "Edit match",
    deleteMatch: "Delete match",
    correctedManually: "Manually corrected",
    matchDeleted: "Match deleted (no match found)",
    minSearchChars: "Enter at least 2 characters to search",
    verdict: "Verdict",
    sourceRyadom: "Source (Ryadom)",
    match: "Match",
    reason: "Reason",
    actions: "Actions",
    searchRyadomProducts: "Search product from Ryadom...",

    // Database
    databaseTitle: "Database",
    databaseSubtitle: "Manage products, prices, and aggregators data",
    import: "Import",
    downloadTemplate: "Download template",
    products: "Products",
    prices: "Prices",
    links: "Links",
    categories: "Categories",
    aggregators: "Aggregators",
    name: "Name",
    color: "Color",
    ourCompany: "Our Company",
    yes: "Yes",
    no: "No",
    icon: "Icon",
    category: "Category",
    position: "Position",
    action: "Action",
    status: "Status",
    priority: "Priority",
    schema: "Schema",
    tables: "Tables",
    totalRecords: "Total Records",
    records: "records",

    // Common
    selectAll: "Select all",
    clearSelection: "Clear selection",
    noData: "No data",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    light: "Light",
    dark: "Dark",
  },

  kz: {
    // Sidebar
    dashboard: "Басқару тақтасы",
    comparison: "Бағаларды салыстыру",
    recommendations: "Ұсыныстар",
    analytics: "Аналитика",
    database: "Дерекқор",
    mappingReview: "Маппинг тексеру",
    priceAnalyst: "Баға талдаушысы",
    glovoPartner: "Ryadom серіктесі",
    optimizeForTop1: "№1 позиция үшін оңтайландыру",

    // Dashboard
    dashboardTitle: "Басқару тақтасы",
    dashboardSubtitle: "Нарықтағы позицияңызды нақты уақытта бақылаңыз",
    refresh: "Жаңарту",
    totalProducts: "Барлық тауарлар",
    inAssortment: "Ассортиментте",
    top1Position: "ТОП 1 позиция",
    ofCatalog: "біздің каталогтың",
    needAction: "Әрекет қажет",
    priceAdjustment: "Баға түзетуі қажет",
    missing: "Жоқ",
    competitorsOnly: "Тек бәсекелестерде",
    awaitingDecision: "Шешім күтуде",
    awaitingActions: "Әрекеттер күтуде",
    potentialSavings: "Ықтимал үнемдеу",
    ifApplyAll: "Барлығын қолданса",
    marketCoverage: "Нарық қамтуы",
    inStock: "Қоймада тауарлар",
    priceCompetitiveness: "Бағалық бәсекеге қабілеттілік",
    inTop1: "ТОП 1 позицияда",
    statusDistribution: "Тауар статустарының таралуы",
    marketCoverageComparison: "Нарық қамтуын салыстыру",
    priceComparison: "Бағаларды салыстыру",
    viewAll: "Барлығын көру",
    minPrice: "Минималды баға",
    productsCount: "тауар",
    leader: "Көшбасшы",
    higherThanLeader: "Көшбасшыдан қымбат",
    moreExpensiveThan: "Қымбатырақ",
    totalAssortment: "Жалпы ассортимент",
    inShopSample: "Дүкен таңдауында",
    marketPositioning: "Нарықтағы позициялау",
    top1Leader: "ТОП-1 (Көшбасшы)",
    aboveMarket: "Нарықтан жоғары",
    missed: "Жіберіп алынған",
    activeSources: "Белсенді дереккөздер",
    ryadom: "Рядом",

    // Comparison
    comparisonTitle: "Баға мониторингі",
    comparisonSubtitle: "Барлық агрегаторлар бойынша бағаларды салыстырыңыз",
    export: "Экспорт",
    searchProducts: "Тауарларды іздеу...",
    allCategories: "Барлық санаттар",
    all: "Барлығы",
    top1: "ТОП 1",
    needActionFilter: "Әрекет қажет",
    missingFilter: "Жоқ",
    showPerUnit: "Кг/л үшін көрсету",
    product: "Тауар",
    ourPosition: "Біздің позиция",
    noProductsFound: "Тауарлар табылмады",
    min: "МИН",
    link: "Сілтеме",
    page: "Бет",
    of: "ішінен",
    back: "Артқа",
    next: "Алға",
    resetFilters: "Сүзгілерді тастау",
    noProductsMatch: "Сүзгілерге сәйкес тауарлар жоқ",

    // ComparisonTable
    noPrice: "Баға жоқ",
    exclusive: "Эксклюзив",
    bestPrice: "Ең жақсы баға",
    moreExpensiveBy: "Қымбатырақ",
    ok: "Ок",
    pricePerUnit: "Бірлік бағасы",
    pricePerItem: "Дана бағасы",
    noDataToDisplay: "Көрсетілетін деректер жоқ",

    // Recommendations
    recommendationsTitle: "Ұсыныстар",
    recommendationsSubtitle: "ТОП-1-ге жету үшін AI баға ұсыныстары",
    showVisualization: "Визуализацияны көрсету",
    hideVisualization: "Визуализацияны жасыру",
    runAlgorithm: "Алгоритмді іске қосу",
    running: "Орындалуда...",
    total: "Барлығы",
    pending: "Күтуде",
    applied: "Қолданылды",
    rejected: "Қабылданбады",
    lowerPrice: "Төмендетілген баға",
    addProduct: "Тауар қосу",
    current: "Ағымдағы",
    recommended: "Ұсынылған",
    notInStock: "Қоймада жоқ",
    savings: "Үнемдеу",
    minCompetitor: "Мин. бәсекелес",
    lowerBy: "төмен",
    apply: "Қолдану",
    applying: "Қолдануда...",
    reject: "Қабылдамау",
    successApplied: "Сәтті қолданылды",
    noRecommendations: "Сіз көшбасшысыз! 🎉",
    noRecommendationsDesc:
      "Ұсыныстар жоқ — барлық бағаларыңыз бәсекеге қабілетті",

    // Priority
    high: "Жоғары",
    medium: "Орта",
    low: "Төмен",

    // Analytics
    analyticsTitle: "Нарық аналитикасы",
    analyticsSubtitle: "Бағалық позицияларды егжей-тегжейлі талдау",
    recommendationsTitle: "Ұсыныстар",
    pricingRecommendations: "Баға белгілеу бойынша AI-ұсыныстары",
    hideVisualization: "Визуализацияны жасыру",
    showVisualization: "Визуализацияны көрсету",
    runAlgorithm: "Алгоритмді іске қосу",
    running: "Орындалуда...",
    total: "Барлығы",
    all: "Барлығы",
    waiting: "Күтуде",
    applied: "Қолданылды",
    rejected: "Қабылданбады",
    lowerPrice: "Төмендетілген баға",
    addProduct: "Өнімді қосу",
    top1coverage: "ТОП-1 қамту",
    importFromApi: "API-ден импорттау",
    confirmRunMatching: "AI өнімдерді сәйкестендіру процесін бастау керек пе? Бұл біраз уақыт алуы мүмкін.",
    matchingStarted: "Сәйкестендіру процесі фонда басталды! Прогресті Бағаларды салыстыру немесе Аналитика бетінен бақылай аласыз.",
    errorMatching: "Сәйкестендіруді бастау кезіндегі қате: ",
    confirmRunImport: "API-ден деректерді импорттауды бастау керек пе?",
    importStarted: "Импорттау фонда басталды. Прогресті Аналитика немесе Бағаларды салыстыру бетінен көруге болады.",
    errorImport: "Импорттауды бастау кезіндегі қате: ",
    productCount: "Өнімдер саны",
    importDataTitle: "Деректерді импорттау",
    importJsonDesc: "JSON файлдарынан өнімдерді импорттау",
    dragDropFile: "Файлды осында сүйреңіз немесе таңдау үшін басыңыз",
    jsonFileLabel: "JSON файлы",
    testRun: "Тестілік іске қосу (сақтаусыз)",
    analyzing: "Талдау...",
    importing: "Импорттау...",
    verify: "Тексеру",
    importAction: "Импорттау",
    analysisCompleted: "Талдау аяқталды",
    importCompleted: "Импорттау аяқталды",
    totalFound: "Барлығы табылды",
    willBeImported: "Импортталады",
    successfully: "Сәтті",
    errorsCount: "Қателер",
    more: "тағы",
    byAggregators: "Агрегаторлар бойынша:",
    byCategories: "Санаттар бойынша:",
    errorsLabel: "Қателер:",
    uploadAnotherFile: "Басқа файлды жүктеу",
    schema: "Схема",
    records: "жазбалар",
    name: "Атауы",
    color: "Түсі",
    ourCompany: "Біздің компания",
    yes: "Иә",
    no: "Жоқ",
    icon: "Иконка",
    category: "Санат",
    position: "Позиция",
    databaseTitle: "Деректер базасын басқару",
    databaseSubtitle: "Деректерді қарау және импорттау",
    loading: "Жүктеу",
    loadingDesc: "Барлық агрегаторлардан тауарлар мен бағаларды жүктеу",
    analysis: "Талдау",
    analysisDesc: "Бәсекелестердің бағаларын салыстыру",
    scarcitySearch: "Дефицитті іздеу",
    scarcitySearchDesc: "Каталогымызда жоқ тауарларды іздеу",
    calculation: "Есептеу",
    calculationDesc: "ТОП-1 үшін оңтайлы бағаларды есептеу",
    generation: "Генерация",
    generationDesc: "Әрекетке арналған ұсыныстарды құру",
    visualizationTitle: "Алгоритм визуализациясы",
    visualizationDesc: "Pricent бағаларды нақты уақыт режимінде қалай талдайтынын көріңіз",
    pause: "Пауза",
    reset: "Сброс",
    analysisResults: "Талдау нәтижелері:",
    analysisCompletedLong: "Талдау аяқталды!",
    recommendationsFound: "ТОП-1-ге жету үшін {count} ұсыныс табылды",
    searchCategories: "Санаттарды іздеу...",
    selectAll: "Барлығын таңдау",
    deselectAll: "Таңдауды алып тастау",
    nothingFound: "Ештеңе табылмады",
    openOn: "Ашу:",
    noData: "Деректер жоқ",
    noDataDesc: "Деректер әзірге жоқ",
    productsNotFound: "Тауарлар табылмады",
    tryChangeFilters: "Іздеу параметрлерін өзгертіп немесе фильтрлерді нөлге түсіріп көріңіз",
    verified: "Тексерілді",
    totalCorrections: "Барлық түзетулер",
    resetFilters: "Фильтрлерді нөлге түсіру",
    dataUnavailable: "Деректер қолжетімсіз",
    uploadDataDesc: "Жұмысты бастау үшін 'Деректер базасы' бөлімі арқылы деректерді жүктеңіз",
    emptyCategoryTitle: "Санат бос",
    emptyCategoryDesc: "Бұл санатта әлі тауарлар жоқ",
    whatChartMeans: "График нені білдіреді",
    chartExplanation: "әр бәсекелестің тауарлар санын көрсетеді. Ассортимент неғұрлым көп болса, нарықтағы бәсекелес соғұрлым күшті болады.",
    errorDuringVerification: "Тексеру кезіндегі қате: ",
    errorSaving: "Сақтау кезіндегі қате: ",
    errorDeleting: "Жою кезіндегі қате: ",
    editMatch: "Матчты өзгерту",
    alreadyInDatabase: "деректер базасында бар",
    priceDynamics: "Баға динамикасы",
    marketShare: "Нарық үлесі",
    marketGaps: "Нарық олқылықтары",
    top5Gaps: "Топ 5 жіберіп алынған мүмкіндік",
    missedOpportunities: "Жіберіп алынған мүмкіндіктер",
    competitorsProducts: "Бәсекелестерде бар тауарлар",
    collapse: "Жию",
    gapAnalysis: "Олқылықтарды талдау",
    gapAnalysisDesc: "Мұнда сіздің көптеген бәсекелестеріңізде бар тауарлар жинақталған. Бұл позицияларды қосу сіздің қамтуыңызды арттыруға және жаңа сатып алушыларды тартуға көмектеседі.",
    popularity: "Танымалдылық",
    minPriceShort: "Мин. баға",
    aggregatorsCount: "агрегатор",
    noGapsToDisplay: "Көрсетілетін жіберіп алынған тауарлар жоқ",
    matchingInProgress: "AI өнімдерді сәйкестендіру жүріп жатыр...",
    matchingCompleted: "Сәйкестендіру аяқталды",
    initializing: "Инициализациялануда...",
    matched: "сәйкестік",
    processed: "өңделді",
    errors: "Қателер",
    importInProgress: "API-ден деректерді импорттау...",
    importCompleted: "Импорт аяқталды",
    preparing: "Дайындық...",
    files: "Файлдар",
    items: "өнімдер",
    productsLower: "өнімдер",
    competitorsAssortment: "Бәсекелестер ассортименті",
    productsPerAggregator: "Әрбір агрегатордағы тауарлар саны",
    whatChartMeans: "График нені білдіреді",
    chartExplanation: "әрбір бәсекелестегі тауарлар санын көрсетеді. Ассортимент неғұрлым көп болса, нарықтағы бәсекелес соғұрлым күшті болады.",
    productsUpper: "ТАУАРЛАР",
    noOverlapData: "Ассортименттің қиылысуы туралы деректер жоқ",
    loadingAnalytics: "Аналитика жүктелуде...",

    // Mapping Review
    mappingReviewTitle: "Маппинг тексеру",
    mappingReviewSubtitle: "Маппингтелген тауарларды қайта тексеру. Дереккөз: bq-results (дерекқорда бар).",
    correctVerdict: "Дұрыс",
    needsReviewVerdict: "Тексеру",
    errorVerdict: "Қате",
    unmappedVerdict: "Маппингтелмеген",
    notFoundVerdict: "Табылмады",
    correctedVerdict: "Түзетілді",
    deletedVerdict: "Жойылды",
    refreshList: "Тізімді жаңарту",
    mappedFilesFromApi: "API-ден маппингтелген файлдар",
    selectMappedFile: "Маппингтелген файлды таңдаңыз",
    selectMappedFileAlert: "Тізімнен маппингтелген файлды таңдаңыз",
    selectFilePlaceholder: "-- Файлды таңдаңыз --",
    limitRecords: "Жазбалар шегі",
    verifyFromApi: "API-ден тексеру",
    sourceLabel: "Дереккөз",
    verifiedSummary: "Тексерілді",
    totalCorrections: "Барлық түзетулер",
    searchPlaceholderMapping: "Атауы немесе себебі бойынша іздеу...",
    allStatuses: "Барлық мәртебелер",
    editMatch: "Матчты өзгерту",
    deleteMatch: "Матчты жою",
    correctedManually: "Қолмен түзетілді",
    matchDeleted: "Матч жойылды (сәйкестік жоқ)",
    minSearchChars: "Іздеу үшін кемінде 2 таңба енгізіңіз",
    verdict: "Үкім",
    sourceRyadom: "Дереккөз (Рядом)",
    match: "Матч",
    reason: "Себебі",
    actions: "Әрекеттер",
    searchRyadomProducts: "Рядом-нан тауар іздеу...",

    // Database
    databaseTitle: "Дерекқор",
    databaseSubtitle: "Тауарлар, бағалар және агрегаторлар деректерін басқару",
    import: "Импорт",
    downloadTemplate: "Үлгіні жүктеу",
    products: "Тауарлар",
    prices: "Бағалар",
    links: "Сілтемелер",
    categories: "Санаттар",
    aggregators: "Агрегаторлар",
    name: "Атауы",
    color: "Түсі",
    ourCompany: "Біздің компания",
    yes: "Иә",
    no: "Жоқ",
    icon: "Белгіше",
    category: "Санат",
    position: "Позиция",
    action: "Әрекет",
    status: "Мәртебе",
    priority: "Басымдық",
    schema: "Схема",
    tables: "Кестелер",
    totalRecords: "Барлық жазбалар",
    records: "жазба",

    // Common
    selectAll: "Барлығын таңдау",
    clearSelection: "Таңдауды алып тастау",
    noData: "Деректер жоқ",
    loading: "Жүктелуде...",
    error: "Қате",
    success: "Сәтті",
    cancel: "Болдырмау",
    save: "Сақтау",
    delete: "Жою",
    edit: "Өңдеу",
    close: "Жабу",
    light: "Жарық",
    dark: "Қараңғы",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    if (typeof window !== "undefined") {
      return localStorage.getItem("language") || "ru";
    }
    return "ru";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.ru[key] || key;
  };

  const languages = [
    { code: "ru", name: "Русский", flag: "" },
    { code: "en", name: "English", flag: "" },
    { code: "kz", name: "Қазақша", flag: "" },
  ];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

export default LanguageContext;
